In [4]:
import numpy as np

a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


## Iteration & Vetorization

In [21]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print('Vectorized version ' + str(1000*(toc-tic)) + ' ms')

c = 0
tic = time.time()
for i in range(100000):
    c += a[i]*b[i]
        
toc = time.time()

print('For loop ' + str(1000*(toc-tic)) + ' ms')

Vectorized version 10.000228881835938 ms
For loop 89.99991416931152 ms


## Python broadcasting & Octave bsxfun

In [25]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.0, 135.0, 99.0, 0.9]])
cal = A.sum(axis=0)
print(cal)

rcal = cal.reshape(4,1);
print('Traspose Cal ' + str(rcal))

per = 100*A/cal # 3x4 / 1x4 It's not necesary to transpose cal
print('Per ' + str(per))
print('Shape Per ' + str(per.shape))

print(np.random.randn(5))
print(np.random.rand(5))
print((np.random.rand(5)).shape)
print((np.random.rand(5,1)).shape)
print((np.random.rand(5)).reshape(5,1).shape)

[  58.2  239.   155.4   76.9]
Traspose Cal [[  58.2]
 [ 239. ]
 [ 155.4]
 [  76.9]]
Per [[ 96.21993127   0.           2.83140283  88.42652796]
 [  2.06185567  43.51464435  33.46203346  10.40312094]
 [  1.71821306  56.48535565  63.70656371   1.17035111]]
Shape Per (3, 4)
[-0.19185967 -0.66244032 -2.38445936 -0.27344586  0.60349552]
[ 0.35606925  0.38961266  0.22302452  0.69850223  0.69195159]
(5,)
(5, 1)
(5, 1)


In [32]:
import numpy as np

a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

print(c)

[[ 1.67089946  1.99070839  0.01517352]
 [ 5.455292    0.46375727  3.33572571]
 [ 0.74652249  2.24134947  1.61702695]]


In [2]:
import numpy as np

A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
print(B.shape)

(4, 1)
